// src/models/Cities.ts

export const MOROCCAN_CITIES: string[] = [
  "Afourer",
  "Agadir",
  "Ahfir",
  "Aït Baha",
  "Aït Ishaq",
  "Aït Melloul",
  "Aït Ourir",
  "Akhfennir",
  "Aklim",
  "Aknoul",
  "Al Hoceïma",
  "Amizmiz",
  "Aoulouz",
  "Aousserd",
  "Arbaoua",
  "Asilah",
  "Assa",
  "Azemmour",
  "Azilal",
  "Azrou",
  "Bab Berred",
  "Béni Mellal",
  "Beni Drar",
  "Benslimane",
  "Berkane",
  "Berrechid",
  "Bhalil",
  "Bin El Ouidane",
  "Biougra",
  "Bir Gandouz",
  "Bir Jdid",
  "Bni Tadjite",
  "Bouarfa",
  "Bouizakarne",
  "Boujdour",
  "Boujniba",
  "Bouskoura",
  "Bouznika",
  "Bradia",
  "Casablanca",
  "Chefchaouen",
  "Chichaoua",
  "Dakhla",
  "Dar Bouazza",
  "Dar Ould Zidouh",
  "Dcheïra El Jihadia",
  "Debdou",
  "Demnate",
  "Deroua",
  "Drargua",
  "El Aïoun Sidi Mellouk",
  "El Gara",
  "El Jadida",
  "El Ksiba",
  "El Marsa",
  "El Ouatia",
  "Errachidia",
  "Es-Semara",
  "Essaouira",
  "Fès",
  "Figuig",
  "Fkih Ben Salah",
  "Fnideq",
  "Guelmim",
  "Guerguerat",
  "Guercif",
  "Guigou",
  "Had Soualem",
  "Harhoura",
  "Igherm",
  "Ifrane",
  "Imintanoute",
  "Imouzzer Kandar",
  "Imouzzer Marmoucha",
  "Imzouren",
  "Inezgane",
  "Jerada",
  "Jorf Lasfar",
  "Jorf El Melha",
  "Kasba Tadla",
  "Kénitra",
  "Khémisset",
  "Khouribga",
  "Ksar El Kébir",
  "Laâyoune",
  "Lahraouyine",
  "Lakhsas",
  "Larache",
  "M'diq",
  "Madagh",
  "Marrakech",
  "Massa",
  "Mechra Bel Ksiri",
  "Médiouna",
  "Midar",
  "Midelt",
  "Mirleft",
  "Mohammedia",
  "Moulay Abdallah",
  "Moulay Bousselham",
  "Nador",
  "Nouaceur",
  "Ouaouizeght",
  "Oualidia",
  "Oulad Ayad",
  "Oulad Azzouz",
  "Oulad Berhil",
  "Oulad M'Barek",
  "Oulad Teïma",
  "Oulad Yaich",
  "Ounagha",
  "Ouarzazate",
  "Oued Amlil",
  "Oujda",
  "Outat El Haj",
  "Rabat",
  "Ribate El Kheir",
  "Saïdia",
  "Safi",
  "Salé",
  "Sebt Gzoula",
  "Sefrou",
  "Settat",
  "Sidi Aïssa",
  "Sidi Bennour",
  "Sidi Boubker",
  "Sidi Bouzid",
  "Sidi Ifni",
  "Sidi Kacem",
  "Sidi Rahal Chataï",
  "Sidi Slimane",
  "Skhirat",
  "Smara",
  "Souk El Arbaa",
  "Souk Sebt Oulad Nemma",
  "Tafraout",
  "Tahannaout",
  "Tahla",
  "Taliouine",
  "Talsint",
  "Tanger",
  "Tan-Tan",
  "Tarafaya",
  "Taroudant",
  "Tata",
  "Taza",
  "Témara",
  "Tendrara",
  "Tétouan",
  "Tinghir",
  "Tit Mellil",
  "Tiznit",
  "Touissit",
  "Youssoufia",
  "Zag",
  "Zagora",
  "Zaïo"
].sort((a, b) => a.localeCompare(b, 'fr'));
